name = "protein-binder-v041-ronig-qwen30b-thinking-train-b64-os10-s2-lr3e06-t10"
model = "Qwen/Qwen3-30B-A3B-Thinking-2507"
max_steps = 2
batch_size = 64
rollouts_per_example = 1
max_async_level = 1
oversampling_factor = 1.0
learning_rate = 3e-06

[sampling]
temperature = 1.0

[[env]]
id = "d42me/protein-binder-monomer-real@0.4.1"

[val]
num_examples = 12
rollouts_per_example = 1
interval = 1

[infrastructure]
compute_size = "S"
